export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const REORDER_INGREDIENTS = 'REORDER_INGREDIENTS';

export const RESET_BURGER_CONSTRUCTOR = 'RESET_BURGER_CONSTRUCTOR';